#!/usr/bin/env ruby
#
# It's snowing!
#

require_relative '../lib/mini_term'

begin
  MiniTerm.open

  if ARGV[0]
    start = ARGV[0].hex

    if ARGV[1]
      finish = ARGV[1].hex
      snow_flakes = (start..finish).map {|c| c.chr(Encoding::UTF_8)}
    else
      snow_flakes = [start.chr(Encoding::UTF_8)]
    end

  else
    snow_flakes = ["*"]
  end

  gen = Random.new

  y_limit, x_limit = MiniTerm.term_info

  loop do
    x = gen.rand(x_limit)
    y = gen.rand(y_limit)

    if (x < (x_limit-1)) || (y < (y_limit-1))
      MiniTerm.set_posn(row: y, column: x)
      snow_flakes.shuffle!
      MiniTerm.print(snow_flakes[0])
    end

    x = gen.rand(x_limit)
    y = gen.rand(y_limit)

    if (x < (x_limit-1)) || (y < (y_limit-1))
      MiniTerm.set_posn(row: y, column: x)
      MiniTerm.print(" ")
    end

    break if MiniTerm.raw(&:has_raw_char?)
  end

ensure
  MiniTerm.getch
  MiniTerm.clear_screen
  MiniTerm.close
end