#!/usr/bin/env ruby
#
# Test raw byte sequences coming from the keyboard.
#

require_relative '../lib/mini_term'

puts "Testing Raw Keyboard input. Press Q to quit."
MiniTerm.open(pass_ctrl_s: true, pass_ctrl_c: true)
key = nil

MiniTerm.raw do |i|
  until key == "Q"
    key = MiniTerm.get_raw_char
    print "[" + "%02X" % key.bytes[0] + "]"
  end
end

MiniTerm.close
puts
puts
